from django.urls import path
from . import views

app_name = 'vehicles'

urlpatterns = [
    path('vehicles/', views.VehicleListCreateView.as_view(), name='vehicle-list'),
    path('vehicles/nearest/', views.nearest_vehicles, name='vehicle-nearest'),
    path('vehicles/<int:pk>/', views.VehicleDetailView.as_view(), name='vehicle-detail'),
    path('vehicles/<int:pk>/update-location/', views.update_location, name='vehicle-update-location'),
    path('vehicles/<int:pk>/assign-driver/', views.assign_driver, name='vehicle-assign-driver'),
    path('vehicles/<int:pk>/dispatch/transition/', views.dispatch_transition, name='vehicle-dispatch-transition'),
    path('dispatch/active/', views.active_dispatch, name='active-dispatch'),
    path('drivers/', views.DriverListCreateView.as_view(), name='driver-list'),
    path('drivers/me/', views.driver_me, name='driver-me'),
    path('drivers/me/change-password/', views.driver_change_password, name='driver-change-password'),
    path('drivers/reset-password/', views.reset_password, name='driver-reset-password'),
    path('drivers/verify-identity/', views.verify_driver_identity, name='driver-verify-identity'),
    path('drivers/me/duty/', views.driver_duty, name='driver-duty'),
    path('drivers/me/dispatch/', views.driver_dispatch, name='driver-dispatch'),
    path('drivers/me/dispatch/transition/', views.driver_dispatch_transition, name='driver-dispatch-transition'),
    path('drivers/me/trip-history/', views.driver_trip_history, name='driver-trip-history'),
    path('drivers/me/notifications/', views.driver_notifications, name='driver-notifications'),
    path('drivers/<int:pk>/', views.DriverDetailView.as_view(), name='driver-detail'),
    path('dispatch/', views.dispatch_vehicle, name='dispatch'),
    path('maintenance/', views.MaintenanceRecordListCreateView.as_view(), name='maintenance-list'),
    path('maintenance/<int:pk>/', views.MaintenanceRecordDetailView.as_view(), name='maintenance-detail'),
    path('maintenance/upcoming/', views.upcoming_maintenance, name='maintenance-upcoming'),
    path('maintenance-templates/', views.MaintenanceTemplateListCreateView.as_view(), name='maintenance-template-list'),
    path('maintenance-templates/<int:pk>/', views.MaintenanceTemplateDetailView.as_view(), name='maintenance-template-detail'),
    path('maintenance-templates/<int:pk>/apply/', views.apply_maintenance_template, name='maintenance-template-apply'),
    path('drivers/me/report-issue/', views.report_issue, name='driver-report-issue'),
    path('issues/', views.issue_report_list, name='issue-report-list'),
    path('issues/<int:pk>/', views.issue_report_detail, name='issue-report-detail'),
    path('emergency/requests/', views.emergency_request_list, name='emergency-request-list'),
    path('emergency/requests/create/', views.create_emergency_request, name='emergency-request-create'),
    path('emergency/requests/<int:pk>/', views.emergency_request_detail, name='emergency-request-detail'),
    path('emergency/requests/<int:pk>/dispatch/', views.emergency_request_dispatch, name='emergency-request-dispatch'),
    path('emergency/requests/<int:pk>/resolve/', views.emergency_request_resolve, name='emergency-request-resolve'),
]
