# Generated by Django 5.2.15 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(default='Default Org', max_length=255),
        ),
    ]
