# Generated by Django 5.2.16 on 2026-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_organization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_app_activity',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time the driver was active on the mobile app (for offline detection)', null=True),
        ),
    ]
