# Generated by Django 5.2.15 on 2026-09-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_last_app_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('organization_type', models.CharField(blank=True, max_length=50)),
                ('contact_information', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORGANIZATION_ADMIN', 'Organization Admin'), ('FLEET_MANAGER', 'Fleet Manager'), ('OFFICER', 'Officer'), ('DRIVER', 'Driver'), ('AUDITOR', 'Auditor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.organization'),
        ),
    ]
