"""
Django settings for sarthi_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------- GeoDjango: GDAL / GEOS paths (Windows - OSGeo4W) ----------
# This MUST be configured before any Django GIS imports happen (e.g. database
# backend loading), so it lives at the top of settings.

if os.name == 'nt':  # Windows
    # Dynamically find the OSGeo4W installation path to support different PCs
    possible_paths = [
        r'C:\OSGeo4W',  # Typical system-wide install (e.g., friend's PC)
        os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Programs', 'OSGeo4W'),  # User-specific install (e.g., your PC)
        r'C:\Users\lenovo\AppData\Local\Programs\OSGeo4W'  # Fallback
    ]
    
    OSGEO4W = None
    for p in possible_paths:
        if p and os.path.isdir(p):
            OSGEO4W = p
            break
            
    if OSGEO4W:
        os.environ['OSGEO4W_ROOT'] = OSGEO4W
        os.environ['GDAL_DATA'] = os.path.join(OSGEO4W, 'share', 'gdal')
        os.environ['PROJ_LIB'] = os.path.join(OSGEO4W, 'share', 'proj')
        bin_path = os.path.join(OSGEO4W, 'bin')
        os.environ['PATH'] = bin_path + ';' + os.environ['PATH']
    
    # Python 3.8+ requires explicitly adding DLL directories for ctypes
    if hasattr(os, 'add_dll_directory'):
        try:
            os.add_dll_directory(bin_path)
        except (FileNotFoundError, OSError):
            pass

    # Workaround for WinError 127: pre-load OSGeo4W's sqlite3.dll so that 
    # Windows doesn't mistakenly load Python's built-in sqlite3.dll when 
    # resolving GDAL's dependencies.
    import ctypes
    try:
        ctypes.CDLL(os.path.join(bin_path, 'sqlite3.dll'))
    except Exception:
        pass

    GDAL_LIBRARY_PATH = os.path.join(bin_path, 'gdal313.dll')
    GEOS_LIBRARY_PATH = os.path.join(bin_path, 'geos_c.dll')
    SPATIALITE_LIBRARY_PATH = os.path.join(bin_path, 'mod_spatialite.dll')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-su$t5h7_k!hque+q3r4y2#uys#1-0^69%wsl5vxjj9muj!r!&$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # GeoDjango
    'django.contrib.gis',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local apps
    'vehicles',
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sarthi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sarthi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'devpass',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# ---------- CORS (allow React dev server) ----------
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
