# Generated by Django 6.0.7 on 2026-07-11 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('logistics', 'Logistics'), ('municipal', 'Municipal')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Current GPS location of the vehicle (lng, lat)', srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
