# Generated by Django 5.2.16 on 2026-07-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_add_owner_to_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='en_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time a GPS update was received from this vehicle', null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dispatchrequest',
            index=models.Index(fields=['status', 'created_at'], name='vehicles_di_status_94dca2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchrequest',
            index=models.Index(fields=['vehicle_type', 'status'], name='vehicles_di_vehicle_392580_idx'),
        ),
    ]
