# Generated by Django 5.2.16 on 2026-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_number_plate_driver_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Real road distance to assigned vehicle at dispatch time (OSRM)', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='duration_min',
            field=models.FloatField(blank=True, help_text='Estimated travel time at dispatch time (OSRM), in minutes', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='used_osrm',
            field=models.BooleanField(default=False, help_text='True if distance/duration came from OSRM; False if straight-line fallback'),
        ),
    ]
