# Generated by Django 5.2.16 on 2026-07-18 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_maintenancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveIndex(
            model_name='maintenancerecord',
            name='vehicles_ma_vehicle_6bf238_idx',
        ),
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='service_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='next_service_due',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='service_type',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'due_date'], name='vehicles_ma_vehicle_cf8c53_idx'),
        ),
    ]
