# Generated by Django 5.2.16 on 2026-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_add_user_to_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_on_duty',
            field=models.BooleanField(db_index=True, default=False, help_text='Driver duty status. When True the assigned vehicle is available.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='admin_blocked',
            field=models.BooleanField(default=False, help_text='Admin override. When True the vehicle is unavailable regardless of driver duty.'),
        ),
    ]
