# Generated by Django 5.2.15 on 2026-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_driver_is_on_duty_vehicle_admin_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='requires_password_change',
            field=models.BooleanField(default=True, help_text='Forces driver to change password on first login.'),
        ),
    ]
