# Generated by Django 5.2.15 on 2026-07-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_driver_requires_password_change'),
        ('vehicles', '0011_issuereport'),
    ]

    operations = [
    ]
