# Generated by Django 5.2.16 on 2026-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_issuereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='resolved',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', db_index=True, max_length=20),
        ),
    ]
