# Generated by Django 5.2.16 on 2026-07-24 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_replace_resolved_with_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='recurrence_days',
            field=models.IntegerField(blank=True, help_text='Repeat every N days (calendar-based recurrence)', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='recurrence_km',
            field=models.IntegerField(blank=True, help_text='Repeat every N km driven (GPS-based recurrence)', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_distance_km',
            field=models.FloatField(default=0, help_text='Cumulative GPS-derived distance (approximate, not true odometer). Updated via location updates with noise filtering.'),
        ),
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g., "Standard Oil Change")', max_length=100)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('recurrence_days', models.IntegerField(blank=True, help_text='Repeat every N days (optional)', null=True)),
                ('recurrence_km', models.IntegerField(blank=True, help_text='Repeat every N km driven (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='vehicles_ma_owner_i_0ef5e9_idx')],
            },
        ),
    ]
