# Generated by Django 5.2.15 on 2026-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_images/'),
        ),
    ]
