# Generated by Django 5.2.15 on 2026-07-31 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_maintenancerecord_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.DecimalField(decimal_places=2, help_text='Amount of fuel added in litres.', max_digits=8)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, help_text='Price per litre in NPR.', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total fuel cost in NPR.', max_digits=10)),
                ('odometer_km', models.DecimalField(blank=True, decimal_places=1, help_text='Odometer reading at the time of fuelling (km).', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('fueled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time of the fuel fill-up.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(help_text='The driver who logged the fuel entry.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='vehicles.driver')),
                ('vehicle', models.ForeignKey(help_text='The vehicle that was refuelled.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-fueled_at'],
                'indexes': [models.Index(fields=['driver', 'fueled_at'], name='vehicles_fu_driver__bc80eb_idx'), models.Index(fields=['vehicle', 'fueled_at'], name='vehicles_fu_vehicle_c4f791_idx')],
            },
        ),
    ]
