# Generated by Django 5.2.16 on 2026-07-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_fuelentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Driver who completed this maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_records', to='vehicles.driver'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes from the person who completed the maintenance'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Photo evidence of completed maintenance', null=True, upload_to='maintenance_proofs/'),
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total fuel cost in NPR.', max_digits=10)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=1, help_text='Odometer reading at the time of fuelling (km).', max_digits=10, null=True)),
                ('receipt_image', models.ImageField(blank=True, help_text='Photo of the fuel receipt.', null=True, upload_to='fuel_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(help_text='The driver who logged the fuel expense.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.driver')),
                ('vehicle', models.ForeignKey(help_text='The vehicle that was refuelled.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'created_at'], name='vehicles_fu_driver__9b3022_idx'), models.Index(fields=['vehicle', 'created_at'], name='vehicles_fu_vehicle_507b4e_idx')],
            },
        ),
    ]
