# Generated by Django 5.2.16 on 2026-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_maintenancerecord_completed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], help_text='Type of fuel.', max_length=10, unique=True)),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Current price per liter in NPR.', max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this price was updated.')),
                ('source', models.CharField(default='NOC', help_text='Data source (e.g., NOC, manual).', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['fuel_type'],
            },
        ),
        migrations.AddField(
            model_name='fuellog',
            name='cost_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per liter in NPR at time of entry.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], default='petrol', help_text='Type of fuel (Petrol or Diesel)', max_length=10),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume of fuel in liters.', max_digits=8, null=True),
        ),
    ]
