# Generated by Django 5.2.16 on 2026-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_migrate_fuelentry_to_fuellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the maintenance in NPR', max_digits=10, null=True),
        ),
    ]
