# Generated by Django 5.2.15 on 2026-08-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_add_cost_to_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('issue', 'Issue'), ('admin', 'Admin'), ('system', 'System'), ('emergency', 'Emergency'), ('fuel', 'Fuel')], default='system', max_length=20),
        ),
    ]
