# Generated by Django 5.2.16 on 2026-08-05 02:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_add_cost_to_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS fix (lng, lat)', srid=4326)),
                ('speed_kmh', models.FloatField(default=0, help_text='Speed at the time of this fix, if reported.')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatch', models.ForeignKey(blank=True, help_text='Active dispatch at the time of this fix, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to='vehicles.dispatchrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='vehicles_lo_vehicle_7053dc_idx'), models.Index(fields=['dispatch', 'recorded_at'], name='vehicles_lo_dispatc_823614_idx')],
            },
        ),
    ]
