# Generated by Django 5.2.16 on 2026-08-05 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_locationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('harsh_accel', 'Harsh acceleration'), ('harsh_brake', 'Hard braking'), ('harsh_turn', 'Harsh turn')], max_length=20)),
                ('severity', models.FloatField(default=1.0, help_text='Magnitude relative to the detection threshold (>=1 means an event).')),
                ('speed_kmh', models.FloatField(default=0, help_text='Vehicle speed at event time.')),
                ('value', models.FloatField(default=0, help_text='Measured magnitude (m/s^2 or degrees).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_events', to='vehicles.dispatchrequest')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_events', to='vehicles.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'created_at'], name='vehicles_dr_driver__837afb_idx'), models.Index(fields=['vehicle', 'created_at'], name='vehicles_dr_vehicle_c054b7_idx')],
            },
        ),
    ]
