# Generated by Django 5.2.15 on 2026-08-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_alter_notification_notification_type'),
        ('vehicles', '0024_drivingevent'),
    ]

    operations = [
    ]
