# Generated by Django 5.2.15 on 2026-08-11 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_merge_20260809_1148'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand / model name (e.g. Toyota Hiace)', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], default='petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.FloatField(default=0, help_text='Current odometer reading in km.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Vehicle photo (JPG/PNG/WebP, max 5 MB)', null=True, upload_to='vehicle_photos/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('on_route', 'On Route'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='offline', help_text='Rich operational status. Derived/updated alongside is_available.', max_length=15),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('logistics', 'Logistics'), ('municipal', 'Municipal'), ('public_transport', 'Public Transport'), ('rental', 'Rental'), ('personal', 'Personal'), ('company', 'Company')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('issue', 'Issue'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('logistics', 'Logistics'), ('municipal', 'Municipal'), ('public_transport', 'Public Transport'), ('rental', 'Rental'), ('personal', 'Personal'), ('company', 'Company')], max_length=20),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable route name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_name', models.CharField(help_text='Start location name', max_length=200)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_name', models.CharField(help_text='End / destination name', max_length=200)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('expected_distance_km', models.FloatField(blank=True, help_text='Expected total route distance in km (admin-entered or OSRM-derived)', null=True)),
                ('expected_duration_min', models.FloatField(blank=True, help_text='Expected travel duration in minutes', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position in the route (0 = first)')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='vehicles.route')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, help_text='Stated purpose of vehicle use', max_length=300)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('expected_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='vehicles.dispatchrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='vehicles.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_id_number', models.CharField(blank=True, help_text='Government ID / citizenship number', max_length=100)),
                ('rental_type', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit (day/hour/week/month) in NPR', max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit in NPR', max_digits=10)),
                ('start_datetime', models.DateTimeField()),
                ('expected_return_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_odometer_km', models.FloatField(blank=True, null=True)),
                ('end_odometer_km', models.FloatField(blank=True, null=True)),
                ('start_location_name', models.CharField(blank=True, max_length=200)),
                ('end_location_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('overdue', 'Overdue'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='reserved', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='vehicles_re_vehicle_2d9b35_idx'), models.Index(fields=['owner', 'status', 'created_at'], name='vehicles_re_owner_i_7f40c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['owner', 'is_active'], name='vehicles_ro_owner_i_524d16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'status'], name='vehicles_ve_vehicle_df976d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='vehicles_ve_user_id_f659a4_idx'),
        ),
    ]
