# Generated by Django 5.2.15 on 2026-08-23 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_phase1_vehicle_photo_route_rental_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_requests', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('on_route', 'On Route'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('retired', 'Retired')], db_index=True, default='offline', help_text='Rich operational status. Derived/updated alongside is_available.', max_length=15),
        ),
    ]
