# Generated by Django 5.2.15 on 2026-08-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0027_alter_dispatchrequest_assigned_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrequest',
            name='vehicle_type',
            field=models.CharField(choices=[('government', 'Government'), ('logistics', 'Logistics'), ('public_transport', 'Public Transport'), ('rental', 'Rental'), ('personal', 'Personal'), ('company', 'Company')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('government', 'Government'), ('logistics', 'Logistics'), ('public_transport', 'Public Transport'), ('rental', 'Rental'), ('personal', 'Personal'), ('company', 'Company')], max_length=20),
        ),
    ]
