# Generated by Django 5.2.15 on 2026-09-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_profile_role_profile_organization'),
        ('vehicles', '0028_alter_dispatchrequest_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fleet_type', models.CharField(choices=[('RENTAL', 'Rental'), ('LOGISTICS', 'Logistics'), ('PUBLIC_TRANSPORT', 'Public Transport'), ('ORGANIZATION', 'Organization'), ('GOVERNMENT', 'Government'), ('MUNICIPAL', 'Municipal'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vehicles.fleet'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.fleet'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('RENTAL', 'Rental'), ('DELIVERY', 'Delivery'), ('PASSENGER_SERVICE', 'Passenger Service'), ('OFFICIAL', 'Official'), ('EMERGENCY', 'Emergency'), ('PERSONAL', 'Personal'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('start_location', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.driver')),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.fleet')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='generic_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_dispatch', to='vehicles.trip'),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Active generic trip at the time of this fix.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to='vehicles.trip'),
        ),
        migrations.AddField(
            model_name='rental',
            name='generic_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_rental', to='vehicles.trip'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='generic_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_assignment', to='vehicles.trip'),
        ),
    ]
