# Generated by Django 5.2.15 on 2026-09-01 06:15

from django.db import migrations

def create_defaults(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    Profile = apps.get_model('accounts', 'Profile')
    Fleet = apps.get_model('vehicles', 'Fleet')
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    Driver = apps.get_model('vehicles', 'Driver')

    # Get the default org name based on existing profiles
    first_profile = Profile.objects.exclude(organization_name='Default Org').order_by('user_id').first()
    if not first_profile:
        first_profile = Profile.objects.order_by('user_id').first()
    org_name = first_profile.organization_name if first_profile else 'Default Organization'
    
    # Create the default organization
    default_org, _ = Organization.objects.get_or_create(
        name=org_name,
        defaults={'organization_type': 'Legacy'}
    )

    # Assign organization to profiles
    for profile in Profile.objects.all():
        profile.organization = default_org
        if profile.user.is_superuser:
            profile.role = 'SUPER_ADMIN'
        else:
            profile.role = 'DRIVER' if Driver.objects.filter(user=profile.user).exists() else 'VIEWER'
        profile.save()

    # Create default fleets based on distinct vehicle types
    fleet_map = {}
    for v_type in Vehicle.objects.values_list('vehicle_type', flat=True).distinct():
        fleet, _ = Fleet.objects.get_or_create(
            organization=default_org,
            name=f"{v_type.title()} Fleet",
            defaults={'fleet_type': v_type.upper()}
        )
        fleet_map[v_type] = fleet

    # Assign org and fleet to vehicles
    for vehicle in Vehicle.objects.all():
        vehicle.organization = default_org
        vehicle.fleet = fleet_map.get(vehicle.vehicle_type)
        vehicle.save()

    # Assign org and fleet to drivers based on their assigned vehicles
    for driver in Driver.objects.all():
        driver.organization = default_org
        # Assign to first assigned vehicle's fleet, if any
        first_vehicle = driver.assigned_vehicles.first()
        if first_vehicle and first_vehicle.fleet:
            driver.fleet = first_vehicle.fleet
        driver.save()

def revert_defaults(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0029_driver_organization_vehicle_organization_fleet_and_more'),
        ('accounts', '0004_organization_profile_role_profile_organization'),
    ]

    operations = [
        migrations.RunPython(create_defaults, revert_defaults),
    ]
