# Generated by Django 5.2.15 on 2026-09-01 06:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_profile_role_profile_organization'),
        ('vehicles', '0030_create_default_org_and_fleet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('SPEED_LIMIT', 'Speed Limit'), ('GEOFENCE', 'Geofence'), ('ROUTE_DEVIATION', 'Route Deviation'), ('UNAUTHORIZED_USE', 'Unauthorized Use'), ('OPERATING_HOURS', 'Operating Hours')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('configuration', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vehicles.fleet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(default='active', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.organization')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vehicles.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_alerts', to='vehicles.rule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
