# Generated by Django 5.2.15 on 2026-09-01 07:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_profile_role_profile_organization'),
        ('vehicles', '0031_rule_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Destination (for logistics)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Pickup or Incident location', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='request_type',
            field=models.CharField(choices=[('LOGISTICS', 'Logistics'), ('EMERGENCY', 'Emergency')], default='EMERGENCY', max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='required_capability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='score_weights',
            field=models.JSONField(blank=True, help_text='Weights used during dispatch engine scoring', null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='request_lat',
            field=models.FloatField(blank=True, help_text='Latitude of the dispatch request', null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='request_lng',
            field=models.FloatField(blank=True, help_text='Longitude of the dispatch request', null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Legacy)'), ('assigned', 'Assigned (Legacy)'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('en_route', 'En Route (Legacy)'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('CREATED', 'Created'), ('SEARCHING', 'Searching'), ('RECOMMENDED', 'Recommended'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('IN_PROGRESS', 'In Progress'), ('NO_VEHICLE_AVAILABLE', 'No Vehicle Available')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
