# Generated by Django 5.2.15 on 2026-09-05 06:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_profile_role_profile_organization'),
        ('vehicles', '0034_add_fuel_type_and_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('police_station', 'Police Station'), ('fire_station', 'Fire Station'), ('government_office', 'Government Office'), ('bus_park', 'Bus Park'), ('warehouse', 'Warehouse'), ('company_location', 'Company Location'), ('fleet_depot', 'Fleet Depot'), ('landmark', 'Registered Landmark'), ('other', 'Other Operational Location')], db_index=True, default='landmark', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Exact authoritative coordinates', srid=4326)),
                ('access_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Optional road access navigation point', null=True, srid=4326)),
                ('organization_name', models.CharField(blank=True, default='', help_text='Scoped to org name or empty for public/emergency landmarks', max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='vehicles_re_vehicle_2d9b35_idx',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='vehicles_re_owner_i_7f40c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='vehicles_ro_owner_i_524d16_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleassignment',
            name='vehicles_ve_vehicle_df976d_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleassignment',
            name='vehicles_ve_user_id_f659a4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='access_lat',
            field=models.FloatField(blank=True, help_text='Road access navigation latitude', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='access_lng',
            field=models.FloatField(blank=True, help_text='Road access navigation longitude', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='address',
            field=models.TextField(blank=True, help_text='Human-readable address or locality description', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who initiated the dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='in_service_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='location_name',
            field=models.CharField(blank=True, help_text='Name of landmark, venue, or building', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='selection_reason',
            field=models.TextField(blank=True, help_text='Explainable reason for vehicle recommendation and assignment', null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_requests', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Destination (for logistics/rentals)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='request_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Dispatch'), ('EMERGENCY', 'Emergency Dispatch')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('CREATED', 'Created'), ('SEARCHING', 'Searching'), ('RECOMMENDED', 'Recommended'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('IN_PROGRESS', 'In Progress'), ('NO_VEHICLE_AVAILABLE', 'No Vehicle Available')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to='vehicles.trip'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='generic_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='vehicles.trip'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per unit in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='expected_distance_km',
            field=models.FloatField(blank=True, help_text='Expected total route distance in km', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand / model name', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_km',
            field=models.FloatField(default=0, help_text='Current odometer reading in km'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('in_use', 'In Use'), ('on_route', 'On Route'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicleassignment',
            name='generic_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='vehicles.trip'),
        ),
    ]
