# Generated by Django 5.2.15 on 2026-09-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0035_operationallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='breakdown_reason',
            field=models.TextField(blank=True, help_text='Reason for breakdown (engine, tire, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='cargo_description',
            field=models.CharField(blank=True, help_text='Cargo / goods description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='cargo_weight_kg',
            field=models.FloatField(blank=True, help_text='Cargo weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='dest_lat',
            field=models.FloatField(blank=True, help_text='Latitude of delivery destination', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='dest_lng',
            field=models.FloatField(blank=True, help_text='Longitude of delivery destination', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='destination_address',
            field=models.TextField(blank=True, help_text='Destination address or depot', null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='destination_name',
            field=models.CharField(blank=True, help_text='Destination landmark or city', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='failed_vehicle',
            field=models.ForeignKey(blank=True, help_text='Broken down vehicle being recovered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_recoveries', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='operation_type',
            field=models.CharField(choices=[('NORMAL_LOGISTICS', 'Normal Logistics Operation'), ('EMERGENCY_REPLACEMENT', 'Emergency Breakdown Replacement')], default='NORMAL_LOGISTICS', max_length=30),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='original_dispatch',
            field=models.ForeignKey(blank=True, help_text='Original logistics delivery if this is an emergency breakdown replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_dispatches', to='vehicles.dispatchrequest'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='related_dispatch',
            field=models.ForeignKey(blank=True, help_text='Original dispatch during which breakdown occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_emergencies', to='vehicles.dispatchrequest'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='replacement_dispatch',
            field=models.ForeignKey(blank=True, help_text='Replacement dispatch sent to recover cargo and complete delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_for_emergencies', to='vehicles.dispatchrequest'),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('CREATED', 'Created'), ('SEARCHING', 'Searching'), ('RECOMMENDED', 'Recommended'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('IN_PROGRESS', 'In Progress'), ('NO_VEHICLE_AVAILABLE', 'No Vehicle Available'), ('EN_ROUTE_TO_PICKUP', 'En Route to Pickup'), ('AT_PICKUP', 'At Pickup'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_AT_DESTINATION', 'Arrived at Destination'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('RECOVERY_IN_PROGRESS', 'Recovery in Progress'), ('EN_ROUTE_TO_BREAKDOWN', 'En Route to Breakdown'), ('AT_BREAKDOWN_LOCATION', 'At Breakdown Location'), ('GOODS_TRANSFERRED', 'Goods Transferred'), ('IN_TRANSIT_TO_DESTINATION', 'In Transit to Destination')], db_index=True, default='pending', max_length=30),
        ),
    ]
