# Generated by Django 5.2.15 on 2026-10-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0036_dispatchrequest_breakdown_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total fuel or charging cost in NPR.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='cost_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per liter or per kWh in NPR at time of entry.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(help_text='The driver who logged the fuel / charging expense.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.driver'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ev', 'EV')], default='petrol', help_text='Type of fuel (Petrol, Diesel, or EV)', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume of fuel in liters or energy in kWh for EV.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle that was refuelled / charged.', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('ev', 'EV')], help_text='Type of fuel or energy.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, help_text='Current price per liter (or per kWh for EV) in NPR.', max_digits=8),
        ),
    ]
