# Generated by Django 5.2.16 on 2026-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_alter_fuellog_amount_alter_fuellog_cost_per_liter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
